sudo : required
services:
  - docker

before install:
  - docker build -t vsriramsscet/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true vsriramsscet/docker-react npm run test -- --coverage