sudo : required
services:
  - docker

before install:
  - docker build -t vsriramsscet/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true vsriramsscet/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "Docker-React"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-294088433019"
  bucket_path: "Docker-React"
  on:
    branch: master
    access_key_id: "$AWS Access Key"
    secret_access_key: "$AWS Secret"